language: python
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy 
python:
  - "2.7"
install:
  - pip install coveralls --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: nosetests -vs tests/ --all-modules --with-coverage --cover-erase --cover-package=.
services: mongodb
before_script:
  - sleep 15

# after_success:
#   - coveralls